### PR TITLE
Fixed https://github.com/martindevans/Cassowary.net/issues/2

### LINKED ISSUE #2: KeyNotFoundException when editing stay variable
The following minimal sample raises a `System.Collections.Generic.KeyNotFoundException` 

```csharp
var value = new ClVariable("value", 0);

var solver = new ClSimplexSolver();

solver.AddStay(value, ClStrength.Strong);

solver.BeginEdit(value)
    .SuggestValue(value, 25)
    .EndEdit(); // <- Exception raised here
```

Full stack trace:

```
Test method PixUITests.LayoutSystem.LayoutConstraintSolverTests.TestMinimal threw exception: 
System.Collections.Generic.KeyNotFoundException: A chave fornecida não estava presente no dicionário.
    em System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   em Cassowary.ClLinearExpression.AddVariable(ClAbstractVariable v, Double c, ClAbstractVariable subject, ClTableau solver)
   em Cassowary.ClSimplexSolver.RemoveConstraint(ClConstraint cn)
   em Cassowary.ClSimplexSolver.RemoveEditVar(ClVariable v)
   em Cassowary.ClSimplexSolver.RemoveEditVarsTo(Int32 n)
   em Cassowary.ClSimplexSolver.Cassowary.IEditContext.EndEdit()
   em PixUITests.LayoutSystem.LayoutConstraintSolverTests.TestMinimal()
```

### PR DESCRIPTION
**Pull request by bazilshep**
Fixed https://github.com/martindevans/Cassowary.net/issues/2

All tests pass.

It should be this way according to the original paper. Not sure why this wasn't like this already. Did the old .net framework version do this implicitly? 

https://constraints.cs.washington.edu/solvers/cassowary-tochi.pdf
Page 34:

>A.2.2 Linear Expressions. Instances of the class ClLinearExpression hold a linear
expression and are used in building and representing constraints and in representing the
tableau. A linear expression holds a dictionary of variables and coefficients (the keys are
variables and the values are the corresponding coefficients). **Only variables with nonzero coefficients are included in the dictionary; if a variable is not in this dictionary its
coefficient is assumed to be zero.**

### CODE REVIEW

File: Cassowary/ClLinearExpression.cs [hunk 1]
```diff
@@ -242,7 +242,7 @@ public ClLinearExpression SetVariable(ClAbstractVariable v, double c)
         /// </summary>
         public ClLinearExpression AddVariable(ClAbstractVariable v, double c, ClAbstractVariable subject, ClTableau solver)
         {
-            ClDouble coeff = _terms[v];
+            ClDouble coeff = _terms.ContainsKey(v)?_terms[v]:null;
```
Comment (martindevans) [inline Cassowary/ClLinearExpression.cs]: Rather than ContainsKey followed by getting the value, use [`TryGetValue`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trygetvalue?view=netcore-3.1) to do both operations at once.

File: Cassowary/ClLinearExpression.cs [hunk 2]
```diff
@@ -394,8 +394,9 @@ public double NewSubject(ClAbstractVariable subject)
         ///      v1*c1 + v2*c2 + .. + vn*cn + c
         /// </summary>
         public double CoefficientFor(ClAbstractVariable var)
-        {
-            ClDouble coeff = _terms[var];
+        {
+            
+            ClDouble coeff = _terms.ContainsKey(var) ? _terms[var] : null;
```
Comment (martindevans) [inline Cassowary/ClLinearExpression.cs]: Rather than ContainsKey followed by getting the value, use [`TryGetValue`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trygetvalue?view=netcore-3.1) to do both operations at once.

**Review by martindevans — APPROVED** [review]

**Comment by martindevans** [comment]
Thanks for this PR! I've requested a small change in the review, but it's nothing major so if you don't want to do that I'll merge it in a few days :)

> Not sure why this wasn't like this already. Did the old .net framework version do this implicitly?

Not as far as I know - It looks like this is simple a bug in the original implementation,

File: Cassowary/ClLinearExpression.cs (hunk 1 above)
Comment (bazilshep) [reply Cassowary/ClLinearExpression.cs]: Good point. Fixed

File: Cassowary/ClLinearExpression.cs (hunk 2 above)
Comment (bazilshep) [reply Cassowary/ClLinearExpression.cs]: Good point. Fixed

**Comment by martindevans** [comment]
Thanks very much :)
